### PR TITLE
Added platform_getProcessMemory implementation for win32

### PR DESCRIPTION
**Pull request by SmilyOrg**

### CODE REVIEW

**Comment by bengarney** [comment]
Oh good catch. Is that the One True Way to get memory used?

**Comment by SmilyOrg** [comment]
There are a bunch of different counters you can get, but I think this one is the most relevant. See http://stackoverflow.com/a/64166

**Comment by bengarney** [comment]
Looks like you need psapi.lib to be linked per https://msdn.microsoft.com/en-us/library/windows/desktop/ms683219(v=vs.85).aspx

**Comment by bengarney** [comment]
Still failed. :(

**Pull request merged**
