### PR TITLE
Added Assembly.loadBytes

### PR DESCRIPTION
**Pull request by SmilyOrg**
Seems like the system doesn't like it somewhere down the line, possibly due to it expecting to be at the top of the lua stack - needs investigation!

Don't :airplane: yet!

### CODE REVIEW

**Comment by bengarney** [comment]
@SmilyOrg Are you as excited about this as I am?

**Comment by bengarney** [comment]
@SmilyOrg This is ready for you to test and land whenever you can! I believe it's on your todo list but wanted to clarify it.

**Comment by bengarney** [comment]
Rebased to see if that fixes build.

**Comment by SmilyOrg** [comment]
Ok, landing... will test firehose.

**Comment by SmilyOrg** [comment]
Seems to work on firehose for me!

**Pull request merged**
