### PR TITLE
Integrated NanoVG clipping into the rest of the display tree

### PR DESCRIPTION
**Pull request by SmilyOrg**
nanovg now clips properly in the clip hierarchy

### CODE REVIEW

**Comment by SmilyOrg** [comment]
Yay

**Comment by bengarney** [comment]
Looking good, only nit I have is you appear to have introduced tabs instead of spaces, can you fix that?

**Comment by SmilyOrg** [comment]
Fixed some inconsistencies, but some entire files are with tabs, so I think it's better to have a separate PR for that.

**Comment by bengarney** [comment]
OK. In general I want to match the surroundings - if surroundings are space be space, if tab be tab.

**Comment by SmilyOrg** [comment]
Is this good?

**Comment by bengarney** [comment]
I'm landing it!

**Pull request merged**
