### PR TITLE
Added sound example with looping background music and sound effects

### PR DESCRIPTION
**Pull request by SmilyOrg**
Used to test sound reload #238 and loading of missing files through Audacity #237

### CODE REVIEW

**Comment by bengarney** [comment]
Awesome. Can you remove the icons from this before I land it?

**Comment by bengarney** [comment]
@SmilyOrg  Can you hit this soon?

**Comment by SmilyOrg** [comment]
I had some issues when running the example again, so I want to solve those first.

**Comment by SmilyOrg** [comment]
Seems like a reboot fixed it, anyway, there's a build without icons.

**Pull request merged**
