### PR TITLE
Fixed wrong alpha when cacheAsBitmap is enabled, alpha was premultipl…

### PR DESCRIPTION
**Pull request by SmilyOrg**
…ied all along!

### CODE REVIEW

**Comment by SmilyOrg** [comment]
cacheAsBitmap fails in NanoVG example, will have to investigate if it's because of this change or something else, but it looks like it doesn't make a texture big enough for all of the elements.

**Comment by themuflon** [comment]
That fails before this change.

**Comment by themuflon** [comment]
Ready to be landed?

**Comment by SmilyOrg** [comment]
If so, this PR should be ok. :airplane:

**Pull request merged**
