### PR TITLE
Fix the meaning of Root to mean the SDK dir

### PR DESCRIPTION
**Pull request by themuflon**
Added a "project" parameter to lsc to indicate the root of the project to compile

### CODE REVIEW

**Comment by bengarney** [comment]
Looks good. Ready to land when green.

**Comment by bengarney** [comment]
I think this needs to be rebased :( @themuflon can you clean it up? I can help if needed.

**Comment by themuflon** [comment]
I thought that's what I managed to do? I'll try again.

**Comment by bengarney** [comment]
The diff shows a ton of commits so I think somehow it got messed up... Bad git!

**Comment by themuflon** [comment]
I think I'll just make a new branch based off of master and cherry pick from there.

**Pull request closed without merging**
