### PR TITLE
Added value check for `utHashedString` so that hash table collisions …

### PR DESCRIPTION
**Pull request by SmilyOrg**
…work properly (thanks Jure!)

### CODE REVIEW

**Comment by bengarney** [comment]
Maybe we should add a comment somewhere noting this subtle and important change in functionality?

**Comment by SmilyOrg** [comment]
Class description?

**Comment by themuflon** [comment]
Looks good, changing the comment on the top of the class would be nice.

**Comment by SmilyOrg** [comment]
I think this might be ready now :)

**Pull request merged**
