### PR TITLE
Handle Application Gain/Loose focus events

### PR DESCRIPTION
**Pull request by themuflon**
Seems to work fine on Windows and Android. Should be fine elsewhere too.

### CODE REVIEW

**Comment by bengarney** [comment]
Does this work properly on Android/iOS? Can someone test?

**Comment by themuflon** [comment]
It does on Android, can't test iOS.

**Comment by bengarney** [comment]
Can Tadej test?

**Comment by AgentSmax** [comment]
Tested on iOS, :white_check_mark:

**Comment by bengarney** [comment]
Awesome.

**Pull request merged**
