### PR TITLE
Bump up Android SDK

### PR DESCRIPTION
**Pull request by themuflon**

### CODE REVIEW

**Comment by SmilyOrg** [comment]
Seems good, rebase and I'll land on green?

**Comment by bengarney** [comment]
Why is this needed?

**Comment by themuflon** [comment]
Why do you mean, why is this needed?

**Comment by SmilyOrg** [comment]
From the Trello card by @themuflon:
> Transition to android-15 is hassle free, but when compiling with android-10 it's a bit more difficult. There an option in the AndroidManifest.xml called hardwareAccelerated that isn't supported before android-11. Also, SDLActivity fails to compile for so many reasons... A lot of unsupported APIs. I think we should stick with android-15.

**Comment by SmilyOrg** [comment]
Apparently build box and ben are both happy, so I'm going to land this.

**Pull request merged**
