### PR TITLE
Fixed modest maps crashes and some event rigging

### PR DESCRIPTION
**Pull request by AgentSmax**
Fixed a few Modest Maps crashes regarding markers and added `onZoom` and `onRender` rigging for proper marker updating.

Apparently also removed unnecessary whitespace... thanks FlashDevelop!

### CODE REVIEW

**Comment by SmilyOrg** [comment]
Can you rebase on master?

**Comment by AgentSmax** [comment]
Working on it right now. Still a bit squeamish when rebasing :P

**Comment by AgentSmax** [comment]
Rebased

**Comment by SmilyOrg** [comment]
Would be nicer if whitespace changes were in a separate PR, but it seems good otherwise. Will land on green.

**Comment by AgentSmax** [comment]
Yeah, it was not intentional. Noticed it after commit.

**Pull request merged**
