### PR TITLE
Fixed the Android build breaking with the new android build tools.

### PR DESCRIPTION
**Pull request by SmilyOrg**
This fix has to be synchronized with loomcli (254).

### CODE REVIEW

**Comment by bengarney** [comment]
Can we check against the Android tool version and use the right argument to make this work on both?

**Comment by SmilyOrg** [comment]
Actually this change is for the updated bundled apktool, so we should only need to make sure it also works with previous build tools. I'm not sure what the error is about though.

**Comment by bengarney** [comment]
```
[13:40:47]Step 2/2: Rake (39s)
[13:40:47][Step 2/2] Starting: /usr/local/loom/ruby/bin/ruby /Volumes/Swarley/TeamCity/buildAgent/plugins/rake-runner/rb/runner/rakerunner.rb --rakefile /Volumes/Swarley/TeamCity/buildAgent/work/160782e93c7262a4/build/Swarley package:free_sdk package:universal_sdk
[13:40:47][Step 2/2] in directory: /Volumes/Swarley/TeamCity/buildAgent/work/160782e93c7262a4
[13:40:48][Step 2/2] 
[13:40:48][Step 2/2] Execute package:free_sdk (26s)
[13:41:15][Execute package:free_sdk] 
[13:41:15][Step 2/2] 
[13:41:15][Step 2/2] Execute package:universal_sdk (11s)
[13:41:25][Execute package:universal_sdk] java -jar artifacts/android/apktool.jar d -f artifacts/android/android/LoomDemo.apk pkg/sdk/bin/android
[13:41:26][Execute package:universal_sdk] Input file (pkg/sdk/bin/android) was not found or was not readable.
[13:41:26][Execute package:universal_sdk] 
[13:41:26]
[Execute package:universal_sdk] RuntimeError: Command failed with status (1): [java -jar artifacts/android/apktool.jar d ...]

Stacktrace:
/usr/local/loom/ruby/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/file_utils.rb:53:in `block in create_shell_runner'
/usr/local/loom/ruby/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/file_utils.rb:45:in `call'
/usr/local/loom/ruby/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/file_utils.rb:45:in `sh'
/usr/local/loom/ruby/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/file_utils_ext.rb:40:in `sh'
/Volumes/Swarley/TeamCity/buildAgent/work/160782e93c7262a4/build/Swarley:306:in `decompile_apk'
/Volumes/Swarley/TeamCity/buildAgent/work/160782e93c7262a4/build/Swarley:56:in `block (2 levels) in <top (required)>'
/usr/local/loom/ruby/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:228:in `call'
/usr/local/loom/ruby/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:228:in `block in execute'
/usr/local/loom/ruby/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:223:in `each'
/usr/local/loom/ruby/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:223:in `execute'
/Volumes/Swarley/TeamCity/buildAgent/plugins/rake-runner/rb/runner/rake_ext.rb:262:in `block in execute'
/Volumes/Swarley/TeamCity/buildAgent/plugins/rake-runner/rb/runner/rake_ext.rb:90:in `target_exception_handling'
/Volumes/Swarley/TeamCity/buildAgent/plugins/rake-runner/rb/runner/rake_ext.rb:268:in `execute'
/usr/local/loom/ruby/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:166:in `block in invoke_with_call_chain'
/usr/local/loom/ruby/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/local/loom/ruby/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:159:in `invoke_with_call_chain'
/usr/local/loom/ruby/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:152:in `invoke'
/Volumes/Swarley/TeamCity/buildAgent/plugins/rake-runner/rb/runner/rake_ext.rb:235:in `block in my_invoke_with_call_chain'
/Volumes/Swarley/TeamCity/buildAgent/plugins/rake-runner/rb/runner/rake_ext.rb:90:in `target_exception_handling'
/Volumes/Swarley/TeamCity/buildAgent/plugins/rake-runner/rb/runner/rake_ext.rb:234:in `my_invoke_with_call_chain'
/usr/local/loom/ruby/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:143:in `invoke_task'
/usr/local/loom/ruby/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/usr/local/loom/ruby/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:101:in `each'
/usr/local/loom/ruby/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:101:in `block in top_level'
/usr/local/loom/ruby/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:110:in `run_with_threads'
/usr/local/loom/ruby/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:95:in `top_level'
/usr/local/loom/ruby/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:73:in `block in run'
/Volumes/Swarley/TeamCity/buildAgent/plugins/rake-runner/rb/runner/rake_ext.rb:314:in `standard_exception_handling'
/usr/local/loom/ruby/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:70:in `run'
/Volumes/Swarley/TeamCity/buildAgent/plugins/rake-runner/rb/runner/rake_ext.rb:179:in `run'
/Volumes/Swarley/TeamCity/buildAgent/plugins/rake-runner/rb/runner/rakerunner.rb:40:in `<main>'

Source: /Volumes/Swarley/TeamCity/buildAgent/work/160782e93c7262a4/build/Swarley:306:in `decompile_apk'
[13:41:26][Execute package:universal_sdk] 
[13:41:26][Step 2/2] 
[13:41:26][Step 2/2] Rake aborted!
[13:41:26][Step 2/2] Process exited with code 1
[13:41:26][Step 2/2] Step Rake failed
[13:41:26]Publishing internal artifacts
[13:41:26][Publishing internal artifacts] Sending build.finish.properties.gz file
[13:41:26]Publishing artifacts (7s)
```

**Comment by bengarney** [comment]
Android built an apk however:

```
[13:38:49][Execute build:android] BUILD SUCCESSFUL
[13:38:49][Execute build:android] Total time: 13 seconds
[13:38:49][Execute build:android] cp application/android/bin/LoomDemo-release-unsigned.apk artifacts/android/LoomDemo.apk
[13:38:49][Execute build:android] 
[13:38:49]Process exited with code 0
```

**Comment by SmilyOrg** [comment]
Ok, this should be green. Also some additional fixes on loomcli side.

**Comment by bengarney** [comment]
This needs a new minimum CLI version I think?

**Comment by SmilyOrg** [comment]
How do I know what `MIN_CLI_VERSION` should be set to?

**Comment by bengarney** [comment]
I landed the CLI changes. When it goes up we can use the new version and God help us.

**Comment by SmilyOrg** [comment]
Haha, ok :pray:

**Comment by bengarney** [comment]
You build the new CLI - and it's 1.0.1236

**Comment by SmilyOrg** [comment]
Lets see green!

**Comment by bengarney** [comment]
Green is good!

**Pull request merged**
