### PR TITLE
My 64bit build fixes and some improvements

### PR DESCRIPTION
**Pull request by SmilyOrg**
Some better error reporting + fixes that I needed to make it work with my configuration of Win/Android/OSX/iOS. Also see the CLI PR.

### CODE REVIEW

**Comment by bengarney** [comment]
Please test this by pulling down build artifacts. @themuflon can you test this?

**Comment by bengarney** [comment]
Code changes look OK, proof is in the pudding.

**Comment by SmilyOrg** [comment]
Huh, why is this not green? TeamCity says yes. Maybe it doesn't like PRs in PRs.

@themuflon can you land this into your branch if it worked for you?

**Comment by bengarney** [comment]
It says still building. Did the teamcity project not post success?

**Comment by SmilyOrg** [comment]
Wait a second, I found it erroring, though it didn't report it right or something?

**Comment by themuflon** [comment]
Teamcity reports failure on the main project, but success on 64bit project. I think github picks up only the main one.

**Pull request merged**
