### PR TITLE
Lfl loom modest maps polish

### PR DESCRIPTION
**Pull request by LukeLamothe**

### CODE REVIEW

**Comment by LukeLamothe** [comment]
OK, all ready for Ben Nits(tm) now.  If all good, then I'll apply to the MobileLocation branch and PR that next.  Outstanding ModestMaps items are still:  a) bug with the tile painter with a clogged queue after zooming in too far and b) mobile performance optimsiations.

**Comment by bengarney** [comment]
Build failed:

```
[05:20:43][Execute build:android]     [javac] Compiling 34 source files to /Volumes/Swarley/TeamCity/buildAgent/work/160782e93c7262a4/application/android/bin/classes
[05:20:43][Execute build:android]     [javac] /Volumes/Swarley/TeamCity/buildAgent/work/160782e93c7262a4/application/android/src/co/theengine/loomdemo/LoomHTTP.java:127: error: cannot find symbol
[05:20:43][Execute build:android]     [javac]                 activity.runOnUiThread(new Runnable() {
[05:20:43][Execute build:android]     [javac]                 ^
[05:20:43][Execute build:android]     [javac]   symbol: variable activity
[05:20:43][Execute build:android]     [javac] /Volumes/Swarley/TeamCity/buildAgent/work/160782e93c7262a4/application/android/src/co/theengine/loomdemo/LoomHTTP.java:165: error: cannot find symbol
[05:20:43][Execute build:android]     [javac]                 activity.runOnUiThread(new Runnable() {
[05:20:43][Execute build:android]     [javac]                 ^
[05:20:43][Execute build:android]     [javac]   symbol: variable activity
[05:20:43][Execute build:android]     [javac] /Volumes/Swarley/TeamCity/buildAgent/work/160782e93c7262a4/application/android/src/co/theengine/loomdemo/LoomHTTP.java:188: error: cannot find symbol
[05:20:43][Execute build:android]     [javac]                 activity.runOnUiThread(new Runnable() 
[05:20:43][Execute build:android]     [javac]                 ^
[05:20:43][Execute build:android]     [javac]   symbol:   variable activity
[05:20:43][Execute build:android]     [javac]   location: class LoomHTTP
[05:20:43][Execute build:android]     [javac] /Volumes/Swarley/TeamCity/buildAgent/work/160782e93c7262a4/application/android/src/co/theengine/loomdemo/LoomHTTP.java:202: error: cannot find symbol
[05:20:43][Execute build:android]     [javac]             activity.runOnUiThread(new Runnable() 
[05:20:43][Execute build:android]     [javac]             ^
[05:20:43][Execute build:android]     [javac]   symbol:   variable activity
[05:20:43][Execute build:android]     [javac]   location: class LoomHTTP
[05:20:44][Execute build:android]     [javac] Note: /Volumes/Swarley/TeamCity/buildAgent/work/160782e93c7262a4/application/android/src/co/theengine/loomdemo/LoomHTTP.java uses or overrides a deprecated API.
[05:20:44][Execute build:android]     [javac] Note: Recompile with -Xlint:deprecation for details.
[05:20:44][Execute build:android]     [javac] 4 errors
```

Probably an SDL platform interaction.

FYI we are getting new buildbot infrastructure to allow easier debugging of these issues.

Nitting!

**Comment by bengarney** [comment]
Outside of the platform issue, it looks good. Does cancel abort a request or just set it to be ignored?

**Comment by bengarney** [comment]
(Nitted.)

**Comment by LukeLamothe** [comment]
Cancel does a proper abort as far as our testing across platforms
indicates. Was easy on android and OSX/ios... PITA on Curl!

**Comment by bengarney** [comment]
OK cool. Please fix the Android compiler issue so it's green and I'll land it!

**Comment by LukeLamothe** [comment]
OK, I've fixed the build errors as far as I can tell (it builds locally
now, but still fails on the build box :/).  However, all HTTP operations on
Android crash during onSuccess (and likely as well in onFailure) as follows:

/data/app-lib/com.loomengine.AsyncImageExample-1/libLoomDemo.so
(arena_salloc+276)

/data/app-lib/com.loomengine.AsyncImageExample-1/libLoomDemo.so
(je_realloc+104)

/data/app-lib/com.loomengine.AsyncImageExample-1/libLoomDemo.so
(lmRealloc_inner+14)

/data/app-lib/com.loomengine.AsyncImageExample-1/libLoomDemo.so
(LS::NativeDelegate::pushArgument(char const*) const+178)

/data/app-lib/com.loomengine.AsyncImageExample-1/libLoomDemo.so
(HTTPRequest::respond(void*, loom_HTTPCallbackType, char const*)+18)

/data/app-lib/com.loomengine.AsyncImageExample-1/libLoomDemo.so
(Java_co_theengine_loomdemo_LoomHTTP_onSuccess+46)


I am thinking that this could be due to the change that Miha made WRT
invoking the native delegate on the UI thread and how it differs between
the old Cocos method with a queued event and now with direct calling, as
rolling back to the pre-SDL change causes the HTTP to work fine on Android
again:

-                Cocos2dxGLSurfaceView.mainView.queueEvent(new Runnable() {

+                // TODO: does this require queueEvent?

+                activity.runOnUiThread(new Runnable() {

Thoughts? I've similarly switched over to master, built dev, and tried
running the AsyncImageExample, or ModestMapsExample and the exact same
crash occurs there.  Same thing if I use latest --firehose :/

Luke

**Comment by SmilyOrg** [comment]
Re: HTTP on Android, #300 hopefully fixes that

**Pull request merged**
