### PR TITLE
Changes I had to make for LuaJIT to compile for Android on Windows

### PR DESCRIPTION
**Pull request by SmilyOrg**
... plus installing and having TDM-GCC-64 in path and possibly some other things.

We have to figure out how to clean this up, maybe try creating reproducible build environments with containers or whatever, so we know what we even need for this functionality and/or when to turn it on and when to just copy over the precompiled file.

WIP, don't land.

### CODE REVIEW

**Comment by bengarney** [comment]
@SmilyOrg Is this landable?

**Comment by SmilyOrg** [comment]
I don't think so, I think it breaks if you don't have the right environment. It would require a bit more work for it to be clean.

**Comment by bengarney** [comment]
OK, is it worth doing that at this time?

**Comment by SmilyOrg** [comment]
Not in the immediate future I don't think, we can close this PR for now, but I'd like to keep at least the branch alive.

**Comment by bengarney** [comment]
Let it be so!

**Pull request closed without merging**
