### PR TITLE
Long print (partial) fix

### PR DESCRIPTION
**Pull request by SmilyOrg**
Here are the current limits per-platform:

- Windows & Windows --noconsole & Android & OS X --noconsole (with Ben's fixes): > 3000 chars (not extensively tested, but it should be unlimited)
- OS X & iOS: ~1000 chars

In my testing it did not crash the asset agent on any of the above platforms.

### CODE REVIEW

**Comment by bengarney** [comment]
Failed on windows due to

```
[16:12:36][Step 2/2] 
[16:12:36][Step 2/2] "C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\LoomEngine.sln" (default target) (1) ->
[16:12:36][Step 2/2] "C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
[16:12:36][Step 2/2] "C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj" (default target) (3) ->
[16:12:36][Step 2/2] (ClCompile target) -> 
[16:12:36][Step 2/2]   ..\..\..\loom\common\core\log.c(204): warning C4047: '=' : 'int' differs in levels of indirection from 'va_list' [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[16:12:36][Step 2/2]   ..\..\..\loom\common\core\log.c(204): warning C4047: 'function' : 'va_list' differs in levels of indirection from 'int' [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[16:12:36][Step 2/2]   ..\..\..\loom\common\core\log.c(204): warning C4024: 'loom_log_getArgs' : different types for formal and actual parameter 1 [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[16:12:36][Step 2/2]   ..\..\..\loom\common\core\log.c(204): warning C4047: '=' : 'int' differs in levels of indirection from 'char *' [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[16:12:36][Step 2/2]   ..\..\..\loom\common\core\log.c(204): warning C4047: '=' : 'int' differs in levels of indirection from 'va_list' [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[16:12:36][Step 2/2]   ..\..\..\loom\common\core\log.c(209): warning C4047: 'function' : 'const char *' differs in levels of indirection from 'int' [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[16:12:36][Step 2/2]   ..\..\..\loom\common\core\log.c(209): warning C4024: 'function through pointer' : different types for formal and actual parameter 4 [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[16:12:36][Step 2/2]   ..\..\..\loom\common\core\log.c(213): warning C4022: 'free' : pointer mismatch for actual parameter 1 [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[16:12:36][Step 2/2] 
[16:12:36][Step 2/2] 
[16:12:36][Step 2/2] "C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\LoomEngine.sln" (default target) (1) ->
[16:12:36][Step 2/2] "C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
[16:12:36][Step 2/2] "C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj" (default target) (3) ->
[16:12:36][Step 2/2] (ClCompile target) -> 
[16:12:36][Step 2/2]   ..\..\..\loom\common\core\log.c(203): error C2143: syntax error : missing ';' before 'type' [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[16:12:36][Step 2/2]   ..\..\..\loom\common\core\log.c(204): error C2275: 'va_list' : illegal use of this type as an expression [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[16:12:36][Step 2/2]   ..\..\..\loom\common\core\log.c(204): error C2146: syntax error : missing ';' before identifier 'args' [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[16:12:36][Step 2/2]   ..\..\..\loom\common\core\log.c(204): error C2065: 'args' : undeclared identifier [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[16:12:36][Step 2/2]   ..\..\..\loom\common\core\log.c(204): error C2065: 'args' : undeclared identifier [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[16:12:36][Step 2/2]   ..\..\..\loom\common\core\log.c(204): error C2065: 'buff' : undeclared identifier [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[16:12:36][Step 2/2]   ..\..\..\loom\common\core\log.c(204): error C2065: 'args' : undeclared identifier [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[16:12:36][Step 2/2]   ..\..\..\loom\common\core\log.c(204): error C2065: 'args' : undeclared identifier [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[16:12:36][Step 2/2]   ..\..\..\loom\common\core\log.c(209): error C2065: 'buff' : undeclared identifier [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[16:12:36][Step 2/2]   ..\..\..\loom\common\core\log.c(213): error C2065: 'buff' : undeclared identifier [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[16:12:36][Step 2/2] 
```

and on Mac due to while test. Can you rebase after fixing the windows build?

**Comment by bengarney** [comment]
I opened #303 with fix to the macro causing the errors.

You can view this way to reduce whitespace diff: https://github.com/LoomSDK/LoomSDK/pull/303/files?w=1

**Comment by SmilyOrg** [comment]
Ok, lets see it now! Also updated limits.

**Comment by bengarney** [comment]
Looking good. Two nits:

1. Should we use internal allocators in the log buffer? Or reuse a pool of memory to avoid an alloc per log? If it's right not to use the Loom allocators there, is it documented?
2. There are several blocks of dead code you replace with new logging idioms. Can you please remove them?

Cheers,
Ben

**Comment by SmilyOrg** [comment]
1. We probably should. I'll look into it when I get the chance.
2. Yep, I should clean it up a bit.

**Comment by SmilyOrg** [comment]
Ok, tested on Windows / Android / OS X / iOS with fixes for 1. and 2. Build should also be green now.

**Pull request merged**
