### PR TITLE
Ouya Removal

### PR DESCRIPTION
**Pull request by Newtsuck**
Improvements:
- Completely removed Ouya building to avoid errors

Will the build bot build it? That is the question

### CODE REVIEW

**Comment by bengarney** [comment]
Does this affect CLI? Does it properly error in the absence of Ouya files if you try to do an Ouya operation?

**Comment by Newtsuck** [comment]
Attempting to build Ouya results in this error:
```
error: No such file or directory - c:/Users/Xyden/.loom/sdks/dev/bin/ouya. Use --trace to view backtrace
```
I don't know if this is a "proper" error, but it does cause the process to stop

**Comment by bengarney** [comment]
I'm more concerned if any loom CLI operations block due to missing ouya and/or if we should prepare a parallel pull that modifies the CLI to print a friendly warning about no Ouya support.

**Comment by bengarney** [comment]
Basically I want to make sure the overall Loom product experience reflects this change and gives a consistent experience.

**Pull request merged**
