### PR TITLE
Fixes for ModestMaps pull request

### PR DESCRIPTION
**Pull request by themuflon**

### CODE REVIEW

**Comment by themuflon** [comment]
I assume this is a mac build problem, like before. Haven't touched that yet.

**Comment by themuflon** [comment]
Apparently my VM thought it was Friday and the last commit shows up first. Fixed OSX build.

**Comment by bengarney** [comment]
```
[Step 2/2]   platformHTTPCurl.cpp
[14:47:15][Step 2/2]   platformHttpAndroid.cpp
[14:47:15][Step 2/2]   c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\CL.exe /c /IC:/BuildAgent/work/160782e93c7262a4/cmake_msvc/loom/vendor/sdl2/include /IC:/BuildAgent/work/160782e93c7262a4/loom/vendor/sdl2/include /I"C:/BuildAgent/work/160782e93c7262a4/loom/vendor/jemalloc-3.4.0/include/msvc_compat" /IC:/BuildAgent/work/160782e93c7262a4 /IC:/BuildAgent/work/160782e93c7262a4/loom/vendor /IC:/BuildAgent/work/160782e93c7262a4/loom/vendor/seatest /IC:/BuildAgent/work/160782e93c7262a4/loom/vendor/stb /IC:/BuildAgent/work/160782e93c7262a4/loom/vendor/minimp3 /IC:/BuildAgent/work/160782e93c7262a4/loom/vendor/smslib /IC:/BuildAgent/work/160782e93c7262a4/loom/vendor/geldreich /IC:/BuildAgent/work/160782e93c7262a4/loom/vendor/jansson /IC:/BuildAgent/work/160782e93c7262a4/loom/vendor/admob/include /I"C:/BuildAgent/work/160782e93c7262a4/loom/vendor/jemalloc-3.4.0/include" /IC:/BuildAgent/work/160782e93c7262a4/loom/vendor/teak/ios/Carrot.framework/Headers /IC:/BuildAgent/work/160782e93c7262a4/loom/vendor/sqlite3 /IC:/BuildAgent/work/160782e93c7262a4/loom/vendor/facebook/ios/FacebookSDK.framework/Headers /IC:/BuildAgent/work/160782e93c7262a4/loom/vendor/parse/ios/Parse.framework/Headers /IC:/BuildAgent/work/160782e93c7262a4/loom/vendor/luajit/src /IC:/BuildAgent/work/160782e93c7262a4/loom/vendor/zlib/include /IC:/BuildAgent/work/160782e93c7262a4/loom/vendor/libcurl/include /nologo /W3 /WX /MP8 /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D LOOM_ENABLE_JIT /D CURL_STATICLIB /D LOOM_DISABLE_JEMALLOC /D __STDC_LIMIT_MACROS=1 /D __STDINT_MACROS=1 /D __STDC_CONSTANT_MACROS=1 /D _CRT_SECURE_NO_WARNINGS /D _HAS_EXCEPTIONS=0 /D WIN32 /D _WINDOWS /D Win32 /D FREEGLUT_STATIC /D FREEGLUT_LIB_PRAGMAS=0 /D GLEW_STATIC /D "CMAKE_INTDIR=\"Release\"" /D _MBCS /Gm- /EHsc /MT /GS /arch:SSE2 /fp:precise /Zc:wchar_t /Zc:forScope /GR /Fo"LoomCommon.dir\Release\\" /Fd"C:/BuildAgent/work/160782e93c7262a4/cmake_msvc/loom/common/Release/LoomCommon.pdb" /Gd /TC /wd4819 /analyze- /errorReport:queue ..\..\..\loom\common\assets\assetsImage.c  /Zm1000 
[14:47:15][Step 2/2]   assetsImage.c
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(98): error C2275: 'loom_asset_image_t' : illegal use of this type as an expression [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2]           C:/BuildAgent/work/160782e93c7262a4\loom/common/assets/assetsImage.h(47) : see declaration of 'loom_asset_image_t'
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(98): error C2065: 'img' : undeclared identifier [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(101): error C2065: 'img' : undeclared identifier [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(101): error C2223: left of '->orientation' must point to struct/union [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(103): error C2065: 'img' : undeclared identifier [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(103): error C2223: left of '->bits' must point to struct/union [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(103): error C2065: 'img' : undeclared identifier [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(103): error C2223: left of '->width' must point to struct/union [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(103): error C2065: 'img' : undeclared identifier [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(103): error C2223: left of '->height' must point to struct/union [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(103): error C2065: 'img' : undeclared identifier [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(103): error C2223: left of '->bpp' must point to struct/union [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(103): warning C4047: 'function' : 'int *' differs in levels of indirection from 'int' [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(103): warning C4024: 'stbi_load_from_memory' : different types for formal and actual parameter 3 [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(103): error C2198: 'stbi_load_from_memory' : too few arguments for call [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(107): error C2065: 'img' : undeclared identifier [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(107): error C2223: left of '->bits' must point to struct/union [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(110): error C2065: 'img' : undeclared identifier [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(110): warning C4022: 'lmFree_inner' : pointer mismatch for actual parameter 2 [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(114): error C2065: 'img' : undeclared identifier [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(114): error C2223: left of '->width' must point to struct/union [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(114): error C2065: 'img' : undeclared identifier [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(114): error C2223: left of '->height' must point to struct/union [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(116): error C2065: 'img' : undeclared identifier [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] ..\..\..\loom\common\assets\assetsImage.c(116): warning C4047: 'return' : 'void *' differs in levels of indirection from 'int' [C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj]
[14:47:15][Step 2/2] Done Building Project "C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\common\LoomCommon.vcxproj" (default targets) -- FAILED.
[14:47:15][Step 2/2] Project "C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\ALL_BUILD.vcxproj.metaproj" (2) is building "C:\BuildAgent\work\160782e93c7262a4\cmake_msvc\loom\engine\LoomCore.vcxproj" (4) on node 1 (default targets).
[14:47:15][Step 2/2] InitializeBuildStatus:
[14:47:15][Step 2/2]   Creating "LoomCore.dir\Release\LoomCore.unsuccessfulbuild" because "AlwaysCreate" was specified.
```

Failure on windows.

**Comment by themuflon** [comment]
I still don't get the error, "warnings as errors" were already enabled. It's probably a different VS version.

Anyway, this might fix it.

**Comment by bengarney** [comment]
Looking good. Just one question - why the change on base64 flag behavior on some platforms?

**Pull request merged**
